### ISSUE TITLE
Text not being continuous

### ISSUE THREAD

**Issue by Widvilky** [TimeStepYT/DeltaruneTextboxes#5]
there's like this little bug where it only shows the first dialogue of the keymaster and not the rest (also is present in the shopkeeper)
https://github.com/user-attachments/assets/5a2cfcae-8104-45c9-b494-8c69a665bc87

**Comment by TimeStepYT** [comment]
That's literally the only thing the keymaster says here???

**Comment by TimeStepYT** [comment]
Could you show me what you mean with the shopkeeper? Also the Keymaster dialog is continuous on the versus mode button, which is replaced by the super expert button on your video

**Comment by Traaays** [comment]
😎
