### ISSUE TITLE
Uhhhhh. I found a crash

### ISSUE THREAD

**Issue by Gabriel1813** [TimeStepYT/DeltaruneTextboxes#6]
So whenever u do that one secret where u click the shopkeeper a bunch of times. For some reason when u do that. The game crashes LOL

https://github.com/user-attachments/assets/583c5de9-d549-459a-98c6-2e670ac10dee

**Comment by TimeStepYT** [comment]
I am certain that this was not even my code being shit, this was just because a function wasn't found for 2.207 yet

**Comment by TimeStepYT** [comment]
It literally was, I just found the address so it doesn't crash anymore. Update should get accepted soon by the index staff!

**Comment by Gabriel1813** [comment]
Ty so much
